name: deployment

on:
  push:
    branches: [ main, ci ]

jobs:
  build-and-push-measurement-api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push MeasurementApi
        uses: docker/build-push-action@v5
        with:
          context: ./HealthcareComp/MeasurementApi/
          push: true
          tags: christianhesberg/measurement-api:latest
          
  build-and-push-measurement-service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
          
      - name: Build and push MeasurementService
        uses: docker/build-push-action@v5
        with:
          context: ./HealthcareComp/MeasurementService/
          push: true
          tags: christianhesberg/measurement-service:latest
          
  build-and-push-patient-api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Build and push PatientApi
        uses: docker/build-push-action@v5
        with:
          context: ./HealthcareComp/PatientApi/
          push: true
          tags: christianhesberg/patient-api:latest
          
  build-and-push-patient-service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Build and push PatientService
        uses: docker/build-push-action@v5
        with:
          context: ./HealthcareComp/PatientService/
          push: true
          tags: christianhesberg/patient-service:latest
        