name: deployment

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build-and-push-measurement-api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push MeasurementApi
        uses: docker/build-push-action@v4
        with:
          context: HealthcareComp/
          file: HealthcareComp/MeasurementApi/Dockerfile
          push: true
          tags: christianhesberg/measurement-api:latest
          
  build-and-push-measurement-service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
          
      - name: Build and push MeasurementService
        uses: docker/build-push-action@v4
        with:
          context: HealthcareComp/
          file: HealthcareComp/MeasurementService/Dockerfile
          push: true
          tags: christianhesberg/measurement-service:latest
          
  build-and-push-patient-api:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: Build and push PatientApi
        uses: docker/build-push-action@v4
        with:
          context: HealthcareComp/
          file: HealthcareComp/PatientApi/Dockerfile
          push: true
          tags: christianhesberg/patient-api:latest
          
  build-and-push-patient-service:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
       
      - name: Build and push PatientService
        uses: docker/build-push-action@v4
        with:
          context: HealthcareComp/
          file: HealthcareComp/PatientService/Dockerfile
          push: true
          tags: christianhesberg/patient-service:latest
            
  build-and-push-doctor-ui:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push doctorui
        uses: docker/build-push-action@v4
        with:
          context: DoctorUi/
          file: DoctorUi/Dockerfile
          push: true
          tags: christianhesberg/doctor-ui:latest
        
  build-and-push-patient-ui:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push doctorui
        uses: docker/build-push-action@v4
        with:
          context: PatientUi/
          file: PatientUi/Dockerfile
          push: true
          tags: christianhesberg/patient-ui:latest